services:
  - type: web
    name: arish-portfolio
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./.output/public
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
